# Generated by Django 5.1.3 on 2024-06-17 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
                ('order_number', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('order_updated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Information',
                'verbose_name_plural': 'Payment Informations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SiyazalanaBank',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('order_uuid', models.UUIDField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=300)),
                ('tip', models.CharField(blank=True, max_length=200, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BBGI Finance Information',
                'verbose_name_plural': 'BBGI Finance Informations',
                'ordering': ['-created'],
            },
        ),
    ]
