# Generated by Django 5.1.3 on 2025-01-02 22:48

import accounts.utilities.file_handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='address_one',
        ),
        migrations.AddField(
            model_name='account',
            name='address_two',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='South Africa', max_length=300),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('kzn', 'KwaZulu-Natal'), ('mp', 'Mpumalanga'), ('nw', 'North-West'), ('fs', 'Free-State'), ('wc', 'Western Cape'), ('lp', 'Limpopo'), ('gp', 'Gauteng'), ('ec', 'Eastern Cape'), ('nc', 'Northern Cape')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to=accounts.utilities.file_handlers.handle_profile_upload),
        ),
    ]
