# Generated by Django 5.1.3 on 2024-06-17 22:20

import accounts.utilities.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_account_address_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('address_one', models.CharField(blank=True, max_length=300, null=True)),
                ('address_two', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('province', models.CharField(blank=True, choices=[('kzn', 'KwaZulu-Natal'), ('mp', 'Mpumalanga'), ('nw', 'North-West'), ('fs', 'Free-State'), ('wc', 'Western Cape'), ('lp', 'Limpopo'), ('gp', 'Gauteng'), ('ec', 'Eastern Cape'), ('nc', 'Northern Cape')], max_length=300, null=True)),
                ('country', models.CharField(default='South Africa', max_length=300)),
                ('zipcode', models.BigIntegerField(blank=True, null=True)),
                ('address_id', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('slug', models.SlugField(default='about-siyazalana-model', max_length=300, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('small_description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True, unique=True)),
                ('mission', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'About Company',
                'verbose_name_plural': 'About Companys',
            },
        ),
    ]
