# Generated by Django 5.1.3 on 2025-01-02 21:38

import django.db.models.deletion
import siyazalana_home.utilities.file_handlers
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('label', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=70)),
                ('from_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=500)),
                ('task_id', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/images/team')),
                ('full_names', models.CharField(help_text='Enter member full names', max_length=250)),
                ('slug', models.SlugField(max_length=350)),
                ('role', models.CharField(help_text='Enter member role', max_length=250)),
                ('decription', tinymce.models.HTMLField(blank=True, help_text='Describe the team member', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(choices=[('Website Terms and Community Guidlines', 'Website Terms and Community Guidlines'), ('Refund Policy', 'Refund Policy'), ('Privacy Policy', 'Privacy Policy'), ('Terms of use: Consumers', 'Terms of use: Consumers'), ('Terms of use: Organisers', 'Terms of use: Organisers')], max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=160)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Privacy',
                'verbose_name_plural': 'Privacys',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload news image.', null=True, upload_to=siyazalana_home.utilities.file_handlers.handle_post_file_upload)),
                ('title', models.CharField(help_text='Enter title for your news', max_length=150)),
                ('description', models.CharField(help_text='Write a short description about this post', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='siyazalana_home.blogcategory')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='siyazalana_home.blog')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
