# Generated by Django 5.1.3 on 2025-01-02 21:38

import accounts.utilities.validators
import campaigns.models
import campaigns.utils
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siyazalana_home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload campaign image.', null=True, upload_to=campaigns.utils.handle_campaign_file_upload)),
                ('title', models.CharField(help_text='Enter title for your campaign', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('small_description', models.TextField(blank=True, help_text='Small description about your campaign for search optimization.', null=True)),
                ('details', tinymce.models.HTMLField(help_text='Enter additional details about your campaign')),
                ('target', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter target amount', max_digits=1000)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('phone', models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('alternative_phone', models.CharField(blank=True, help_text='Enter your business number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-8][0-9]{8}$', 'RSA phone number is required')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('website', models.URLField(blank=True, null=True)),
                ('campaign_address', models.CharField(blank=True, help_text='Enter campaign address seperated by comma', max_length=300, null=True)),
                ('map_coordinates', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 1, 2, 21, 37, 59, 145342, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")])),
                ('status', models.CharField(choices=[('NOT APPROVED', 'Not approved'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='NOT APPROVED', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='siyazalana_home.blogcategory')),
                ('organiser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaigns',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Upload emages images.', upload_to='campaigns/images/content/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campaigns.campaignmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignReview',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commenter_email', models.EmailField(max_length=254)),
                ('commenter_full_names', models.CharField(max_length=300)),
                ('comment_title', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaigns.campaignmodel')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Review',
                'verbose_name_plural': 'Campaign Reviews',
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdateModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns.campaignmodel')),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
            },
        ),
        migrations.CreateModel(
            name='ContributionModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_method_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_card_holder', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_masked_card', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method_scheme', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(editable=False, max_length=300, unique=True)),
                ('checkout_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter contribution amount', max_digits=1000)),
                ('tip', models.CharField(choices=[('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%')], default='10%', max_length=25)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('accepted_laws', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('paid', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('NOT PAID', 'Not paid'), ('CANCELLED', 'Cancelled')], default='NOT PAID', max_length=40)),
                ('anonymous', models.BooleanField(default=False)),
                ('receipt', models.FileField(null=True, upload_to='contributions/receipts/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='campaigns.campaignmodel')),
                ('contributor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-created'],
            },
        ),
    ]
