# Generated by Django 5.1.3 on 2025-01-02 22:48

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 1, 2, 22, 48, 47, 498970, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
