# Generated by Django 5.1.3 on 2024-06-17 22:20

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaignmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 6, 17, 22, 20, 8, 495107, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
