# Generated by Django 5.1.3 on 2024-06-18 01:37

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaignmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 6, 18, 1, 36, 50, 27763, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
